name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - 
      name: Checkout the repo
      uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        pull: true
        push: true
        cache-from: type=registry,ref=dylanbulmer/annotator:latest
        cache-to: type=inline
        tags: dylanbulmer/annotator:latest

  deploy: 
    runs-on: self-hosted
    needs: build

    steps:
      - name: Deploy to server
        run: cd ~/projects/annotator && docker-compose up -d